### ISSUE TITLE
Authentication using Web API Key

### ISSUE THREAD

**Issue by Immortalin** [nhedlund/intrinio#12]
The web API key does not require a username/password combo

**Comment by nhedlund** [comment]
Are you sure? When I look at the current documentation from Intrinio they still use username/password combos as API keys: https://intrinio.com/tutorial/web_api

**Comment by eecharlie** [comment]
I had been using your library for a while but dusting off my code that I hadn't touched since March, I'm having the same problem - and at that webpage, I only see examples using an API Key.
I also see that Intrinio released a [intrinio/python-sdk](https://github.com/intrinio/python-sdk) in the last couple months. Can you address the API Key issue, and whether your project still offers utility beyond Intrinio's SDK? Would be awesome to have this upfront in the readme. Thanks!

**Comment by nhedlund** [comment]
Last time I checked they had not added API keys to their documentation but now that they have I will add it to the library. Username and password still works.

Good suggestion, I checked their python-sdk package and from what I can see they do not use Pandas as return types and don't return the complete datasets by default.

**Comment by eecharlie** [comment]
Thanks - I thought I posted another comment last night, but I found out they terminated my free subscriptions. I'm really annoyed that they dropped any free tier of their service, including for existing users, and will probably look at Python libraries that pull from IEX. I don't need anything near real-time pricing data.
What's the unique value that you see in Intrinio over IEX or [other free options](https://www.reddit.com/r/Python/comments/8b5xuw/apis_that_work_for_stock_data/)?

**Comment by nhedlund** [comment]
For me Intrinio gives you split- and dividend-adjusted stock prices that I need for accurate backtesting, for a reasonable monthly price. Quandl is another good provider.

Most or all providers of free stock prices only offer unadjusted data or very limited historic data, at least what I have found.

**Comment by nhedlund** [comment]
It seems that they have changed the API a lot from V1 to V2 that would cause a major rewrite of this library.

Even if I prefer working with Pandas datasets and libraries that returns full datasets instead of using paging it seems better to refer to the official SDK that targets the new API.

**Comment by eecharlie** [comment]
Thanks. If it's helpful, it looks like the Yahoo API can still be made to work with pandas-datareader:
https://towardsdatascience.com/python-for-finance-stock-portfolio-analyses-6da4c3e61054
https://pypi.org/project/fix-yahoo-finance/
I don't know what about the fix is 'temporary', but this API returns a pandas dataframe and included both actual and adjusted (I assume split/dividend) market close numbers.

I've only looked far enough to see that the example walkthrough on the blog post returns data.
